// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: xtouch-pad

#include "../ui.h"

void onDeleteFileConfirm(void *user_data) {
    lv_obj_t *target = (lv_obj_t*)user_data;
    void *full_path = lv_obj_get_user_data(target);
    printf("DELETED : %s\n", (char*)full_path);

    lv_obj_del(target);                                     // delete image
    lv_obj_t *parent = lv_obj_get_parent(target);           // get tile
    if (lv_obj_get_child_cnt(parent) == 0) {                // no image in this tile
        lv_obj_t *grandparent = lv_obj_get_parent(parent);  // get tileview
        lv_obj_del(parent);                                 // remove this tile
        if (grandparent) {                                  // update tileview
            printf("invalidate tileview !!!\n");
            lv_obj_invalidate(grandparent);
            lv_event_send(grandparent, LV_EVENT_SCROLL_END, NULL);
        }
    }
}

void onPrintConfirm(void *user_data) {
    lv_obj_t *target = (lv_obj_t*)user_data;
    void *full_path = lv_obj_get_user_data(target);
    printf("PRINTING : %s\n", (char*)full_path);
}

void ui_event_comp_png(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    lv_obj_t *user_data = lv_event_get_user_data(e);
    void *obj_user_data;
    static bool is_long = false;

    switch (event_code) {
        case LV_EVENT_CLICKED:
            if (!is_long && user_data != NULL) {
                printf("PRINT? : %s\n", (char*)user_data);
                ui_confirmPanel_show(LV_SYMBOL_WARNING " Print ?", onPrintConfirm, target);
            }
            is_long = false;
            break;

        case LV_EVENT_LONG_PRESSED:
            is_long = true;
            break;

        case LV_EVENT_RELEASED:
            if (is_long && user_data != NULL) {
                printf("DELETE? : %s\n", (char*)user_data);
                ui_confirmPanel_show(LV_SYMBOL_WARNING " Delete ?", onDeleteFileConfirm, target);
            }
            break;

        case LV_EVENT_DELETE:
            obj_user_data = lv_obj_get_user_data(target);
            if (obj_user_data) {
                lv_mem_free(obj_user_data);
            }
            break;
    }
}

void add_file(lv_obj_t *tile, char *path, char *fn) {
    char *full_path = lv_mem_alloc(strlen(path) + strlen(fn) + 2);

    strcpy(full_path, path);
    strcat(full_path, "/");
    strcat(full_path, fn);

    lv_obj_t *cui_png = lv_img_create(tile);
    lv_obj_set_width(cui_png, 128);
    lv_obj_set_height(cui_png, 128);
    lv_img_set_src(cui_png, full_path);
    lv_obj_set_align(cui_png, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(cui_png, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_png, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(cui_png, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(cui_png, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(cui_png, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_user_data(cui_png, full_path);
    lv_obj_add_event_cb(cui_png, ui_event_comp_png, LV_EVENT_ALL, full_path);

    lv_obj_t *cui_labelFileName = lv_label_create(cui_png);
    lv_obj_set_width(cui_labelFileName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_labelFileName, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(cui_labelFileName, LV_ALIGN_BOTTOM_MID);
    lv_label_set_long_mode(cui_labelFileName, LV_LABEL_LONG_SCROLL);
    lv_obj_clear_flag(cui_labelFileName, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
            LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_text_color(cui_labelFileName, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_labelFileName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(cui_labelFileName, fn);
}

lv_obj_t *add_tile(lv_obj_t *parent, int row) {
    lv_obj_t *tile = lv_tileview_add_tile(parent, 0, row, LV_DIR_VER);
    lv_obj_set_align(tile, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(tile, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(tile, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);

    return tile;
}

void add_images(lv_obj_t *parent, char *path) {
    lv_fs_dir_t dir;
    lv_fs_res_t res;
    lv_obj_t *tile;
    int cnt = 0;
    const int imgs_per_tile = 4;

    res = lv_fs_dir_open(&dir, path);
    if (res != LV_FS_RES_OK) {
        printf("Failed to open dir !!!\n");
        return;
    }

    char fn[256];

    while (1) {
        res = lv_fs_dir_read(&dir, fn);
        if (res != LV_FS_RES_OK) {
            printf("Failed to read dir !!!\n");
            break;
        }

        /*fn is empty, if not more files to read*/
        if (strlen(fn) == 0) {
            break;
        }

        int len = strlen(fn);
        if (len > 4) {
            char *ext = &fn[len - 4];
            printf("%s, %s\n", fn, ext);

            if (!strcasecmp(ext, ".png")) {
                if (cnt % imgs_per_tile == 0) {
                    tile = add_tile(parent, cnt / imgs_per_tile);
                }
                cnt++;
                add_file(tile, path, fn);
            }
        }
    }

    lv_fs_dir_close(&dir);
}

lv_obj_t *ui_browserComponent_create(lv_obj_t *comp_parent) {
    lv_obj_t *cui_browserComponent = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_browserComponent, lv_pct(85));
    lv_obj_set_height(cui_browserComponent, lv_pct(100));
    lv_obj_clear_flag(cui_browserComponent, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
    lv_obj_set_style_bg_color(cui_browserComponent, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_browserComponent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *cui_sd_browser = lv_label_create(cui_browserComponent);
    lv_obj_set_width(cui_sd_browser, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_sd_browser, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(cui_sd_browser, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(cui_sd_browser, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_sd_browser, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(cui_sd_browser, "SD Card Browser");
    lv_obj_set_style_text_color(cui_sd_browser, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_sd_browser, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_sd_browser, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_sd_browser, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_sd_browser, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_sd_browser, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_sd_browser, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *tv = lv_tileview_create(cui_browserComponent);
    lv_obj_set_width(tv, lv_pct(100));
    lv_obj_set_height(tv, lv_pct(80));
    lv_obj_set_align(tv, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(tv, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    add_images(tv, "S:/image");

    return cui_browserComponent;
}
